from pathlib import Path


def replace_exact(path: Path, old: str, new: str, label: str) -> None:
    text = path.read_text("utf-8")
    if old not in text:
        if new in text:
            return
        raise SystemExit(f"{label} marker changed")
    path.write_text(text.replace(old, new, 1), "utf-8")


def main() -> None:
    path = Path("src/openakita/hub/skill_store_client.py")

    replace_exact(
        path,
        '''import asyncio\nimport json\nimport logging\nimport os\nimport random\nimport shutil\nimport subprocess\nimport sys\n''',
        '''import asyncio\nimport json\nimport logging\nimport os\nimport random\nimport re\nimport secrets\nimport shutil\nimport subprocess\nimport sys\n''',
        "runtime safety imports",
    )
    replace_exact(
        path,
        '''from ..config import settings\n''',
        '''from ..agents.manifest import (\n    MAX_PACKAGE_SIZE,\n    MAX_SINGLE_FILE_SIZE,\n    validate_external_skill_source,\n    validate_file_safety,\n)\nfrom ..config import settings\nfrom ..utils.atomic_io import atomic_json_write, safe_write\n''',
        "shared safety helpers",
    )
    replace_exact(
        path,
        '''            (skill_dir / ".openakita-origin.json").write_text(\n                json.dumps(origin, ensure_ascii=False, indent=2), encoding="utf-8"\n            )\n            # Also write .openakita-source for compatibility with bridge/frontend matching\n            (skill_dir / ".openakita-source").write_text(install_url, encoding="utf-8")\n''',
        '''            atomic_json_write(\n                skill_dir / ".openakita-origin.json",\n                origin,\n                backup=True,\n                fsync=True,\n                allow_fallback=False,\n            )\n            # Also write .openakita-source for compatibility with bridge/frontend matching\n            safe_write(\n                skill_dir / ".openakita-source",\n                install_url,\n                backup=True,\n                fsync=True,\n                allow_fallback=False,\n            )\n''',
        "atomic origin metadata",
    )
    replace_exact(
        path,
        '''        if target_dir is None:\n            target_dir = settings.skills_path\n\n        target_dir.mkdir(parents=True, exist_ok=True)\n\n        if "@" in install_url and "/" in install_url:\n            repo_part, skill_name = install_url.rsplit("@", 1)\n            if not repo_part.startswith("http"):\n                repo_part = f"https://github.com/{repo_part}"\n        else:\n            repo_part = install_url\n            skill_name = install_url.rsplit("/", 1)[-1]\n\n        skill_dir = target_dir / skill_name\n        if skill_dir.exists():\n            logger.info(f"Skill {skill_name} already exists, updating...")\n            shutil.rmtree(skill_dir)\n\n        # Strategy 1: Download cached ZIP from platform\n        if skill_id:\n            try:\n                installed = await self._install_from_platform_cache(skill_id, skill_name, skill_dir)\n                if installed:\n                    self._write_origin(skill_dir, install_url)\n                    logger.info(f"Installed skill from platform cache: {skill_name} -> {skill_dir}")\n                    return skill_dir\n            except Exception as e:\n                logger.debug(f"Platform cache download failed for {skill_id}: {e}")\n                if skill_dir.exists():\n                    shutil.rmtree(skill_dir, ignore_errors=True)\n\n        # Ensure clean state: platform cache may have left a partial skill_dir\n        if skill_dir.exists():\n            shutil.rmtree(skill_dir, ignore_errors=True)\n\n        # Strategy 2: git clone fallback\n        try:\n            installed = await self._install_via_git(repo_part, skill_name, skill_dir)\n            if installed:\n                self._write_origin(skill_dir, install_url)\n                logger.info(f"Installed skill via git: {skill_name} -> {skill_dir}")\n                return skill_dir\n        except Exception as e:\n            logger.debug(f"git clone failed for {skill_name}: {e}")\n            if skill_dir.exists():\n                shutil.rmtree(skill_dir, ignore_errors=True)\n\n        raise RuntimeError(\n            f"Failed to install skill '{skill_name}': "\n            "neither platform cache nor git clone succeeded"\n        )\n''',
        '''        if target_dir is None:\n            target_dir = settings.skills_path\n        target_dir = Path(target_dir).expanduser().resolve()\n        target_dir.mkdir(parents=True, exist_ok=True)\n\n        if not validate_external_skill_source(install_url):\n            raise ValueError(f"Unsafe Skill Store install URL: {install_url!r}")\n\n        if "@" in install_url:\n            repo_part, skill_name = install_url.rsplit("@", 1)\n        else:\n            repo_part = install_url\n            skill_name = repo_part.rstrip("/").rsplit("/", 1)[-1]\n            if skill_name.endswith(".git"):\n                skill_name = skill_name[:-4]\n        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}", skill_name):\n            raise ValueError(f"Unsafe Skill Store skill name: {skill_name!r}")\n        if not repo_part.startswith("http"):\n            repo_part = f"https://github.com/{repo_part}"\n\n        skill_dir = target_dir / skill_name\n        import tempfile\n\n        async def _attempt(strategy: str) -> bool:\n            with tempfile.TemporaryDirectory(\n                dir=target_dir, prefix=f".{skill_name}.stage-"\n            ) as stage_root:\n                staging_dir = Path(stage_root) / "skill"\n                installed = False\n                if strategy == "platform":\n                    installed = await self._install_from_platform_cache(\n                        str(skill_id or ""), skill_name, staging_dir\n                    )\n                else:\n                    installed = await self._install_via_git(repo_part, skill_name, staging_dir)\n                if not installed:\n                    return False\n                self._write_origin(staging_dir, install_url)\n                self._replace_skill_directory(staging_dir, skill_dir)\n                return True\n\n        if skill_id:\n            try:\n                if await _attempt("platform"):\n                    logger.info(\n                        "Installed skill from platform cache: %s -> %s", skill_name, skill_dir\n                    )\n                    return skill_dir\n            except Exception as e:\n                logger.debug("Platform cache download failed for %s: %s", skill_id, e)\n\n        try:\n            if await _attempt("git"):\n                logger.info("Installed skill via git: %s -> %s", skill_name, skill_dir)\n                return skill_dir\n        except Exception as e:\n            logger.debug("git clone failed for %s: %s", skill_name, e)\n\n        raise RuntimeError(\n            f"Failed to install skill '{skill_name}': "\n            "neither platform cache nor git clone succeeded"\n        )\n''',
        "transactional install flow",
    )
    replace_exact(
        path,
        '''        resp = await _retry_request(\n            client,\n            "GET",\n            f"/skills/{skill_id}/download",\n            follow_redirects=True,\n            timeout=60.0,\n        )\n        if resp.status_code != 200:\n            return False\n\n        data = resp.content\n        if len(data) < 22:  # minimum ZIP size\n            return False\n\n        skill_dir.mkdir(parents=True, exist_ok=True)\n        abs_target = str(skill_dir.resolve()) + os.sep\n        with zipfile.ZipFile(io.BytesIO(data)) as zf:\n            for member in zf.namelist():\n                member_path = os.path.normpath(os.path.join(skill_dir.resolve(), member))\n                if not member_path.startswith(abs_target) and member_path != abs_target.rstrip(\n                    os.sep\n                ):\n                    raise RuntimeError(\n                        f"Zip Slip detected: member '{member}' escapes target directory"\n                    )\n            zf.extractall(skill_dir)\n\n        skill_md = skill_dir / "SKILL.md"\n        return skill_md.exists()\n''',
        '''        data = bytearray()\n        async with client.stream(\n            "GET",\n            f"/skills/{skill_id}/download",\n            follow_redirects=True,\n            timeout=60.0,\n        ) as resp:\n            if resp.status_code != 200:\n                return False\n            declared = resp.headers.get("content-length")\n            if declared:\n                try:\n                    if int(declared) > MAX_PACKAGE_SIZE:\n                        raise RuntimeError("Skill ZIP exceeds safety limit")\n                except ValueError:\n                    pass\n            async for chunk in resp.aiter_bytes(1024 * 1024):\n                data.extend(chunk)\n                if len(data) > MAX_PACKAGE_SIZE:\n                    raise RuntimeError("Skill ZIP exceeds safety limit")\n\n        if len(data) < 22:\n            return False\n\n        skill_dir.mkdir(parents=True, exist_ok=True)\n        total = 0\n        seen: set[str] = set()\n        with zipfile.ZipFile(io.BytesIO(bytes(data))) as zf:\n            for info in zf.infolist():\n                errors = validate_file_safety(info.filename)\n                if errors:\n                    raise RuntimeError(f"Unsafe Skill ZIP member: {'; '.join(errors)}")\n                key = "/".join(\n                    part.rstrip(" .").casefold()\n                    for part in info.filename.replace("\\\\", "/").split("/")\n                )\n                if key in seen:\n                    raise RuntimeError(f"Duplicate Skill ZIP member: {info.filename}")\n                seen.add(key)\n                if info.file_size > MAX_SINGLE_FILE_SIZE:\n                    raise RuntimeError(f"Skill ZIP member too large: {info.filename}")\n                total += info.file_size\n                if total > MAX_PACKAGE_SIZE:\n                    raise RuntimeError("Skill ZIP expands beyond safety limit")\n                if info.external_attr >> 16 & 0o120000 == 0o120000:\n                    raise RuntimeError(f"Skill ZIP symlink not allowed: {info.filename}")\n            bad_member = zf.testzip()\n            if bad_member is not None:\n                raise RuntimeError(f"Corrupt Skill ZIP member: {bad_member}")\n            zf.extractall(skill_dir)\n\n        skill_md = skill_dir / "SKILL.md"\n        return skill_md.exists()\n''',
        "bounded validated platform zip",
    )
    replace_exact(
        path,
        '''            result = subprocess.run(\n                [git_exe, "clone", "--depth=1", repo_url, str(tmp_dir)],\n                capture_output=True,\n                text=True,\n                timeout=120,\n                **extra_kwargs,\n            )\n''',
        '''            result = await asyncio.to_thread(\n                subprocess.run,\n                [git_exe, "clone", "--depth=1", repo_url, str(tmp_dir)],\n                capture_output=True,\n                text=True,\n                timeout=120,\n                **extra_kwargs,\n            )\n''',
        "nonblocking git clone",
    )
    replace_exact(
        path,
        '''                    with urllib.request.urlopen(req, timeout=30) as resp:\n                        data = resp.read()\n                    break\n''',
        '''                    def _download() -> bytes:\n                        with urllib.request.urlopen(req, timeout=30) as resp:\n                            declared = resp.headers.get("Content-Length")\n                            if declared:\n                                try:\n                                    if int(declared) > MAX_PACKAGE_SIZE:\n                                        raise RuntimeError("GitHub Skill ZIP exceeds safety limit")\n                                except ValueError:\n                                    pass\n                            payload = resp.read(MAX_PACKAGE_SIZE + 1)\n                            if len(payload) > MAX_PACKAGE_SIZE:\n                                raise RuntimeError("GitHub Skill ZIP exceeds safety limit")\n                            return payload\n\n                    data = await asyncio.to_thread(_download)\n                    break\n''',
        "nonblocking bounded zip fallback",
    )
    replace_exact(
        path,
        '''    @staticmethod\n    def _extract_skill_from_repo(tmp_dir: Path, skill_name: str, skill_dir: Path) -> bool:\n        """Extract skill directory from a cloned/downloaded repo tree."""\n        skill_md_at_root = tmp_dir / "SKILL.md"\n        if skill_md_at_root.exists():\n            shutil.copytree(str(tmp_dir), str(skill_dir))\n            git_dir = skill_dir / ".git"\n            if git_dir.exists():\n                shutil.rmtree(git_dir)\n            return True\n''',
        '''    @staticmethod\n    def _replace_skill_directory(staging_dir: Path, target_dir: Path) -> None:\n        """Atomically swap a prepared Skill into place and restore on failure."""\n        backup_dir = target_dir.with_name(\n            f".{target_dir.name}.backup-{secrets.token_hex(8)}"\n        )\n        had_existing = target_dir.exists()\n        if had_existing:\n            target_dir.replace(backup_dir)\n        try:\n            staging_dir.replace(target_dir)\n        except Exception:\n            if had_existing and backup_dir.exists() and not target_dir.exists():\n                backup_dir.replace(target_dir)\n            raise\n        else:\n            if backup_dir.exists():\n                shutil.rmtree(backup_dir)\n\n    @staticmethod\n    def _copy_skill_tree(source: Path, target: Path) -> None:\n        """Copy a Skill tree without following symlinks or oversized payloads."""\n        target.mkdir(parents=True, exist_ok=True)\n        total = 0\n        for item in source.rglob("*"):\n            if item.is_symlink():\n                raise RuntimeError(f"Skill symlink not allowed: {item}")\n            rel = item.relative_to(source)\n            dest = target / rel\n            if item.is_dir():\n                dest.mkdir(parents=True, exist_ok=True)\n                continue\n            if not item.is_file():\n                continue\n            size = item.stat().st_size\n            if size > MAX_SINGLE_FILE_SIZE:\n                raise RuntimeError(f"Skill file too large: {item}")\n            total += size\n            if total > MAX_PACKAGE_SIZE:\n                raise RuntimeError("Skill tree exceeds safety limit")\n            dest.parent.mkdir(parents=True, exist_ok=True)\n            with item.open("rb") as src, dest.open("wb") as out:\n                shutil.copyfileobj(src, out, length=1024 * 1024)\n\n    @staticmethod\n    def _extract_skill_from_repo(tmp_dir: Path, skill_name: str, skill_dir: Path) -> bool:\n        """Extract skill directory from a cloned/downloaded repo tree."""\n        skill_md_at_root = tmp_dir / "SKILL.md"\n        if skill_md_at_root.exists():\n            SkillStoreClient._copy_skill_tree(tmp_dir, skill_dir)\n            git_dir = skill_dir / ".git"\n            if git_dir.exists():\n                shutil.rmtree(git_dir)\n            return True\n''',
        "transactional copy helpers",
    )
    replace_exact(
        path,
        '''                shutil.copytree(str(candidate), str(skill_dir))\n                return True\n''',
        '''                SkillStoreClient._copy_skill_tree(candidate, skill_dir)\n                return True\n''',
        "safe candidate copy",
    )
    replace_exact(
        path,
        '''                shutil.copytree(str(skill_md.parent), str(skill_dir))\n                return True\n\n        shutil.copytree(str(tmp_dir), str(skill_dir))\n''',
        '''                SkillStoreClient._copy_skill_tree(skill_md.parent, skill_dir)\n                return True\n\n        SkillStoreClient._copy_skill_tree(tmp_dir, skill_dir)\n''',
        "safe fallback copy",
    )


if __name__ == "__main__":
    main()
